version: "3.9"

services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A run_worker worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis:7
